spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate # Never auto-update schema in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # Disable DevTools in production
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Minimal error details in production (config.consider_all_requests_local = false)
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  # Enable if using HTTPS/SSL (config.force_ssl in Rails)
  ssl:
    enabled: ${SSL_ENABLED:false}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Production logging (config.log_level = :debug, but we'll use WARN for root)
logging:
  level:
    root: WARN
    com.adminapplicationmaster: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  # Log to STDOUT if RAILS_LOG_TO_STDOUT is present (like in Rails config)
  file:
    name: ${LOG_FILE:}

server:
  port: ${PORT:8080}