spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_app_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: INFO
    com.adminapplicationmaster: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# External services - use mock/default values for local development
decision:
  service:
    host: http://localhost:8081
    api:
      token: local-dev-token

location:
  service:
    host: http://localhost:8082
    api:
      token: local-dev-token

# Local encryption key
encryption:
  key: local-dev-encryption-key-change-me