# Main application configuration
# Environment-specific settings are in application-{profile}.yml
# Activate profiles: --spring.profiles.active=dev or --spring.profiles.active=prod

spring:
  application:
    name: admin-application-master
  
  # Secret key for session management and JWT (if used)
  # In production, set via environment variable: SECRET_KEY_BASE
  security:
    secret-key: ${SECRET_KEY_BASE:changeme-default-secret-key-for-development-only}
  
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME:admin_app_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${RAILS_MAX_THREADS:5}
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: true

  # Flyway configuration for database migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  
  web:
    resources:
      add-mappings: false

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
    session:
      timeout: 3m 
      cookie:
        http-only: true
        secure: false # Set to true in production
        same-site: lax
  error:
    white-label:
      enabled: false

# External Service Configuration
decision:
  service:
    host: ${DECISION_SERVICE_HOST}
    api:
      token: ${DECISION_SERVICE_API_TOKEN}

location:
  service:
    host: ${LOCATION_SERVICE_HOST}
    api:
      token: ${LOCATION_SERVICE_API_TOKEN}

# Encryption
encryption:
  key: ${ENCRYPTION_KEY}

logging:
  level:
    root: INFO
    com.adminapplicationmaster: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
